[GLOBAL]
pants_version = "2.14.1"
backend_packages = [
    "pants.backend.python"
]

[source]
root_patterns = ["/"]

[python]
interpreter_constraints = ["CPython==3.7.15","==3.7.15"]
# This will become the default in Pants 2.15.
tailor_pex_binary_targets = false

[anonymous-telemetry]
enabled = true
repo_id = "ED3CCABC-6067-47DD-A959-353BC3F02836"
