[GLOBAL]
pants_version = "2.14.0"
backend_packages = [
    "pants.backend.python"
]

[python]
#interpreter_constraints = "==3.7.*"
# This will become the default in Pants 2.15.
tailor_pex_binary_targets = false
enable_resolves = true

[anonymous-telemetry]
enabled = true
repo_id = "ED3CCABC-6067-47DD-A959-353BC3F02836"

[python.resolves]
My_Resolve = "3rdparty/python/my_resolve.lock"

[python.resolves_to_interpreter_constraints]
My_Resolve = ["==3.7.*"]
